spring:
  application:
    name: product-catalog-api
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  threads:
    virtual:
      enabled: true

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Currency exchange configuration
currency:
  exchange:
    frankfurter-api-url: https://api.frankfurter.app/latest?from=EUR&to=USD
