spring:
  application:
    name: product-catalog-api
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  threads:
    virtual:
      enabled: true

  # Distributed tracing configuration
  tracing:
    sampling:
      probability: 1.0
    baggage:
      remote-fields:
        - transaction-id
      correlation:
        fields:
          - transaction-id
    otel:
      exporter:
        otlp:
          endpoint: http://tempo:4317

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,tracing
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
    baggage:
      correlation:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Currency exchange configuration
currency:
  exchange:
    frankfurter-api-url: https://api.frankfurter.app/latest?from=EUR&to=USD
