spring:
  application:
    name: product-catalog-api
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  threads:
    virtual:
      enabled: true

  cache:
    type: caffeine
    cache-names: currency
    caffeine:
      spec: expireAfterWrite=10s

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
    enabled: true

otel:
  metrics:
    exporter: none
  logs:
    exporter: none

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Currency exchange configuration
currency:
  exchange:
    frankfurter-api-url: https://api.frankfurter.app/latest?

# Logging configuration
logging:
  level:
    com.example.demo: DEBUG
